spring:
  application:
    name: WeatherAlertService
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:file:/WeatherAlertService/db/subscriptions
    driver-class-name: org.h2.Driver
    username: sa
    password:
  web:
    allow-circular-references: true
    resources:
      static-locations: classpath:/static/
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_SENDER}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

weather:
  api:
    key: ${WEATHER_API_KEY}

server:
  address: 0.0.0.0